"""is_admin issue

Revision ID: 44000a2c7b9e
Revises: 065f3d8e132e
Create Date: 2025-03-13 11:41:56.909430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44000a2c7b9e'
down_revision: Union[str, None] = '065f3d8e132e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('admin', 'vendor', 'user', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('admin', 'vendor', 'user', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###
