"""add FTS trigger for category

Revision ID: 7b3e2136a558
Revises: ee968d49a490
Create Date: 2025-03-14 10:48:17.321091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b3e2136a558'
down_revision: Union[str, None] = 'ee968d49a490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
               CREATE FUNCTION update_category_tsvector() RETURNS trigger AS $$
               BEGIN
               NEW.name_tsv := to_tsvector('english', NEW.category_name);
               RETURN NEW;
               END;
               $$ LANGUAGE plpgsql;
               """)
    op.execute("""
               CREATE TRIGGER category_tsv_update BEFORE INSERT OR UPDATE
               ON category FOR EACH ROW EXECUTE FUNCTION update_category_tsvector();
               """)

    op.execute("UPDATE category SET name_tsv = to_tsvector('english', category_name);")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('admin', 'vendor', 'user', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###
