"""category name

Revision ID: c306ce44147c
Revises: 44000a2c7b9e
Create Date: 2025-03-13 14:23:03.091396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c306ce44147c'
down_revision: Union[str, None] = '44000a2c7b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('category', 'name')
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('admin', 'vendor', 'user', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('admin', 'vendor', 'user', name='userrole'),
               nullable=True)
    op.add_column('category', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('category', 'category_name')
    # ### end Alembic commands ###
