"""add cascade delete

Revision ID: ee0378713686
Revises: 7b3e2136a558
Create Date: 2025-03-17 12:08:30.258060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee0378713686'
down_revision: Union[str, None] = '7b3e2136a558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('productcategory_product_id_fkey', 'productcategory', type_='foreignkey')
    op.drop_constraint('productcategory_category_id_fkey', 'productcategory', type_='foreignkey')
    op.create_foreign_key(None, 'productcategory', 'product', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'productcategory', 'category', ['category_id'], ['category_id'], ondelete='CASCADE')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('admin', 'vendor', 'user', name='userrole'),
               nullable=True)
    op.drop_constraint(None, 'productcategory', type_='foreignkey')
    op.drop_constraint(None, 'productcategory', type_='foreignkey')
    op.create_foreign_key('productcategory_category_id_fkey', 'productcategory', 'category', ['category_id'], ['category_id'])
    op.create_foreign_key('productcategory_product_id_fkey', 'productcategory', 'product', ['product_id'], ['product_id'])
    # ### end Alembic commands ###
