"""add FTS trigger for category name

Revision ID: ee968d49a490
Revises: cfd9cfab7850
Create Date: 2025-03-14 10:43:12.497194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee968d49a490'
down_revision: Union[str, None] = 'cfd9cfab7850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('name_tsv', postgresql.TSVECTOR(), nullable=True))
    op.create_index(op.f('ix_category_name_tsv'), 'category', ['name_tsv'], unique=False, postgresql_using='gin')

    # Create trigger to update `name_tsv`


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('admin', 'vendor', 'user', name='userrole'),
               nullable=True)
    op.drop_index(op.f('ix_category_name_tsv'), table_name='category')
    op.drop_column('category', 'name_tsv')
    # ### end Alembic commands ###
